const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const model = {};
const path = require('node:path').join(__dirname, '../desktop/BackupModel.js');
assert.ok(fs.existsSync(path), 'Backup request model must exist');
vm.createContext(model);
vm.runInContext(fs.readFileSync(path, 'utf8').replace(/^\.pragma library\s*/, ''), model);
assert.equal(model.validate({destination:'/mnt/backup', configurations:false, files:false}, 'backup'), 'backupChooseScope');
assert.equal(model.validate({destination:'', configurations:true}, 'plan'), 'backupChooseDestination');
assert.equal(model.validate({destination:'/mnt/backup', configurations:true, encrypted:true}, 'backup'), 'backupChooseRecipient');
assert.equal(model.validate({destination:'/mnt/backup', configurations:true}, 'restore'), 'backupChooseRestore');
assert.equal(model.validate({destination:'/mnt/backup', configurations:true, target:'/tmp/recovery', snapshot:'latest'}, 'restore'), '');
assert.equal(model.validate({destination:'/mnt/backup', configurations:true, encrypted:false}, 'backup'), '');
assert.equal(model.validate({destination:'/mnt/backup', encrypted:true, target:'/tmp/recovery', snapshot:'latest'}, 'restore'), 'backupChooseIdentity');
assert.equal(model.validate({destination:'relative', configurations:true}, 'plan'), 'backupAbsoluteDestination');
assert.equal(model.validate({destination:'capsule:', transport:'sftp', files:true}, 'plan'), 'backupRemoteDestination');
assert.equal(model.validate({destination:'capsule:backups', transport:'sftp', files:true}, 'plan'), '');
const tc = {host:'vq-timecapsule.local', address:'192.168.1.15', mac:'5C:96:9D:6D:B2:4A', user:'andres', share:'Data', savedCredential:true};
assert.equal(model.validate({destination:tc, transport:'timecapsule', configurations:true, encrypted:false}, 'plan'), 'backupTimeCapsuleEncryptionRequired');
assert.equal(model.validate({destination:tc, transport:'timecapsule', configurations:true, encrypted:true, ageRecipient:'age1' + 'a'.repeat(58)}, 'plan'), '');
assert.equal(model.wizardCanContinue(1, {destination:tc, destinationKind:'timecapsule', verified:true}), true);
assert.deepEqual(JSON.parse(JSON.stringify(model.request({destination:tc, transport:'timecapsule', configurations:true, encrypted:true, ageRecipient:'age1' + 'a'.repeat(58), password:'never'}, 'plan'))).destination, tc);
assert.equal(model.validate({destination:'/mnt/backup', files:true, paths:['../secret']}, 'plan'), 'backupRelativePaths');
assert.equal(model.validate({destination:'/mnt/backup', files:true, encrypted:true, ageRecipient:'private key'}, 'plan'), 'backupChooseRecipient');
const request = model.request({destination:'/mnt/backup', configurations:true, files:true, pathsText:'Documents\nPictures', encrypted:false, ageRecipient:'stale', password:'never'}, 'plan');
assert.deepEqual(JSON.parse(JSON.stringify(request)), {destination:'/mnt/backup', transport:'local', configurations:true, files:true, encrypted:false, paths:['Documents','Pictures']});
assert.equal(model.request({destination:'/mnt/backup', files:true, pathsText:''}, 'plan').paths[0], '.');
assert.equal(model.parseResponse('{"ok":true,"missing":[]}',0).ok, true);
assert.equal(model.parseResponse('{"ok":true}',1).ok, false);
assert.equal(model.parseResponse('not json',0).ok, false);
assert.equal(model.parseResponse('{"ok":false,"error":"Disk full"}',1).error, 'Disk full');
assert.equal(model.canConfirm({ok:true,missing:[]}, request, request), true);
assert.equal(model.canConfirm({ok:true,missing:['rsync']}, request, request), false);
assert.equal(model.canConfirm({ok:true,missing:[]}, request, {...request, destination:'/other'}), false);
assert.equal(model.canConfirm({ok:false,missing:[]}, request, request), false);
assert.equal(model.validate({destination:'capsule:../backup', transport:'sftp', files:true}, 'plan'), 'backupRemoteDestination');
assert.equal(model.validate({destination:'/mnt/backup', files:true, paths:['/etc']}, 'plan'), 'backupRelativePaths');
assert.equal(model.validate({destination:'/mnt/backup', configurations:true, encrypted:true, ageRecipient:'age1' + 'a'.repeat(58)}, 'plan'), '');
const restore = model.request({destination:'/mnt/backup', configurations:true, files:true, snapshot:'fixture-id', encrypted:true, identityFile:'/media/key.txt', ageRecipient:'irrelevant', target:'/tmp/recovery'}, 'restore');
assert.deepEqual(JSON.parse(JSON.stringify(restore)), {destination:'/mnt/backup', transport:'local', configurations:false, files:false, encrypted:true, snapshot:'fixture-id', target:'/tmp/recovery', identityFile:'/media/key.txt'});
const page = fs.readFileSync(require('node:path').join(__dirname, '../desktop/BackupPage.qml'), 'utf8');
const catalog = JSON.parse(fs.readFileSync(require('node:path').join(__dirname, '../desktop/i18n.json'), 'utf8'));
const keys = [...(page + fs.readFileSync(path, 'utf8')).matchAll(/["'](backup[A-Z][A-Za-z]+)["']/g)].map(match => match[1]);
keys.push('controlPanelTitle', 'close');
for (const lang of ['en', 'es']) for (const key of keys) assert.ok(catalog[lang][key], `${lang} translation missing: ${key}`);
const core = fs.readFileSync(require('node:path').join(__dirname, '../desktop/Core.qml'), 'utf8');
assert.match(core, /t\(uiLang, "backup"\)[\s\S]*?t\(uiLang, "profiles"\)/);
assert.match(core, /NetworkDevicesPage\s*\{[^}]*currentTab === 5/);
assert.match(core, /BackupPage\s*\{[^}]*currentTab === 6/);
assert.match(core, /\/\/ ---------- Profiles ----------[\s\S]*?currentTab === 7/);
assert.equal(typeof model.wizardCanContinue, 'function', 'wizard navigation helper exists');
assert.equal(model.wizardCanContinue(0, {intent:'backup', destinationKind:'timecapsule'}), true);
assert.equal(model.wizardCanContinue(0, {intent:'', destinationKind:'local'}), false);
assert.equal(model.wizardCanContinue(1, {destination:'/mnt/share', verified:false}), false);
assert.equal(model.wizardCanContinue(1, {destination:'/mnt/share', verified:true}), true);
assert.equal(model.wizardCanContinue(2, {intent:'backup', configurations:false, files:true}), true);
assert.equal(model.wizardCanContinue(2, {intent:'restore', snapshot:'id', target:'/tmp/staging', encrypted:true}), false);
assert.equal(typeof model.safeRecoveryKey, 'function');
assert.equal(model.safeRecoveryKey('/mnt/backup/key.key', '/mnt/backup'), false);
assert.equal(model.safeRecoveryKey('/mnt/backup/../key.key', '/mnt/backup'), false);
assert.equal(model.safeRecoveryKey('/safe/key.txt', '/mnt/backup'), false);
assert.equal(model.safeRecoveryKey('/safe/key.key', '/mnt/backup'), true);
assert.equal(model.safeRecoveryKey('/mnt/backups/key.key', '/mnt/backup/'), true);
assert.equal(typeof model.connectionErrorKey, 'function');
assert.equal(model.connectionErrorKey('not_connected'), 'backupNoMounts');
assert.equal(model.connectionErrorKey('missing_tool'), 'backupConnectionMissing');
assert.equal(model.connectionErrorKey('destination_inside_home'), 'backupDiskHelp');
assert.equal(model.connectionErrorKey('unexpected'), 'backupConnectionFailed');
console.log('BackupModel tests passed');
